Raise required toolchain on macos to 1.54.0
    error: linking with `cc` failed: exit status: 1
      |
      = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.0.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.1.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.10.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.11.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.12.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.13.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.2.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.3.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.4.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.5.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.6.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.7.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.8.rcgu.o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.build_script_build.bhr2yx6z-cgu.9.rcgu.o" "-o" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/build/link-cplusplus-97ae727f20aa6669/build_script_build-97ae727f20aa6669.5arif5ebd0zwd810.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/deps" "-L" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/runner/work/link-cplusplus/link-cplusplus/target/debug/deps/libcc-6aedd59b55a24e70.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-f4a73f2c70e583e1.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-b41e562edf698ab1.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-2a4df4c2256492de.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-6aebf63c63f128f7.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-91bb9fde6bea50b4.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd_detect-0046ab440646372a.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-9ae8cf74422b8f0c.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-cf93ef7a59a8cd79.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-2a57083a9622d5ba.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-81882c7eecd5bf0e.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-01c4d0a0963e224a.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-482192be7675f505.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-5104ab1bec4ed881.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-7b1ea7b508ec1c03.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-a124ffd13a55a195.rlib" "/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-160a7dd17f2dc334.rlib" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv"
      = note: ld: in /Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-f4a73f2c70e583e1.rlib(lib.rmeta), archive member 'lib.rmeta' with length 6508696 is not mach-o or llvm bitcode file '/Users/runner/.rustup/toolchains/1.53.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-f4a73f2c70e583e1.rlib'
              clang: error: linker command failed with exit code 1 (use -v to see invocation)