Raise minimum tested compiler on Windows to 1.52
Required by some new code in the cc crate.

    error[E0658]: use of unstable library feature 'str_split_once': newly added
      --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.85\src\windows\find_tools.rs:59:43
       |
    59 |     let target = impl_::TargetArch(target.split_once('-')?.0);
       |                                           ^^^^^^^^^^