Raise minimum tested compiler to 1.45
Required by use of str::strip_suffix in the `cc` crate.

    error[E0658]: use of unstable library feature 'str_strip': newly added
        --> github.com-1ecc6299db9ec823/cc-1.0.80/src/lib.rs:2937:33
         |
    2937 |             .and_then(|var| var.strip_suffix("-gcc").map(str::to_string));
         |                                 ^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'str_strip': newly added
        --> github.com-1ecc6299db9ec823/cc-1.0.80/src/lib.rs:3786:34
         |
    3786 |         if let Some(path) = dirs.strip_prefix("programs: =") {
         |                                  ^^^^^^^^^^^^