Raise minimum tested compiler to 1.53
Required by a use of an IntoIterator for arrays in the cc crate.

    error[E0277]: `[OsString; 6]` is not an iterator
        --> cc-1.0.88/src/lib.rs:2611:29
         |
    2611 |               cmd.args.extend([
         |  _____________________________^
    2612 | |                 // Header search path
    2613 | |                 OsString::from("-isystem"),
    2614 | |                 ios_support.join("/usr/include").into(),
    ...    |
    2632 | |                 },
    2633 | |             ]);
         | |_____________^ expected an implementor of trait `IntoIterator`
         |
         = note: the trait bound `[OsString; 6]: IntoIterator` is not satisfied
         = note: required because of the requirements on the impl of `IntoIterator` for `[OsString; 6]`
    help: consider borrowing here
         |
    2611 |             cmd.args.extend(&[
    2612 |                 // Header search path
    2613 |                 OsString::from("-isystem"),
    2614 |                 ios_support.join("/usr/include").into(),
    2615 |                 // Framework header search path
    2616 |                 OsString::from("-iframework"),
       ...